#!/bin/bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

fullname () {
  local myDIR=`dirname "$1"`
  pushd "$myDIR" >/dev/null
  realDIR=`pwd`
  popd > /dev/null
  local basefile=`basename "$1"`
  echo "$realDIR/$basefile"
}

SCRIPT_NAME=`fullname $0`
FGLCMDIR=`dirname $SCRIPT_NAME` 
export LANG="en_US.UTF-8"
if [ -z "$FGLCM_EXT_DIR" ]
then
  export FGLCM_EXT_DIR="$FGLCMDIR/ext"
fi
export FGLLDPATH="$FGLCM_EXT_DIR:$FGLCMDIR:$FGLCMDIR/fglwebrun:$FGLLDPATH"
#we recompile everything always: hence avoid version clashes
make -C $FGLCMDIR clean_prog all > /dev/null
export FGLCMDIR
FGLCM_LOGFILE=`mktemp`
rm -f $FGLCM_LOGFILE
export FGLCM_LOGFILE="$FGLCM_LOGFILE.log"
echo "logging into $FGLCM_LOGFILE" 
exec fglrun --start-guilog=$FGLCM_LOGFILE $FGLCMDIR/fglcm_main.42m "$@" 
