#!/bin/bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

fullname () {
  local myDIR=`dirname "$1"`
  pushd "$myDIR" >/dev/null
  realDIR=`pwd`
  popd > /dev/null
  local basefile=`basename "$1"`
  echo "$realDIR/$basefile"
}

SCRIPT_NAME=`fullname $0`
export LANG="en_US.UTF-8"
FGLCMDIR=`dirname $SCRIPT_NAME` 
#we recompile everything always: hence avoid version clashes
make -C $FGLCMDIR clean_prog all > /dev/null
export FGLCMDIR
if [ -z "$FGLCM_EXT_DIR" ]
then
  export FGLCM_EXT_DIR="$FGLCMDIR/ext"
fi
export FGLRESOUREPATH=$FGLCMDIR:$FGLRESOURPATH
export DBPATH=$FGLCMDIR:$DBPATH
exec $FGLCMDIR/fglwebrun/fglwebrun $FGLCMDIR/fglcm_main.42m "$@" 
